
version: '3.8'

services:
  localstack:
    container_name: "localstack-awscd"
    image: localstack/localstack:0.12.11
    network_mode: bridge
    privileged: true
    ports:
      - "4566:4566"
    environment:
      - SERVICES=
      - DATA_DIR=/tmp/localstack
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./volume/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"